### ISSUE TITLE
csc.uaf.edu is improperly configured

### ISSUE THREAD

**Issue by TechSolomon** [UAFCSC/uafcsc.github.io#24]
The custom domain for your GitHub Pages site is pointed at an outdated IP address. You must update your site's DNS records if you'd like it to be available via your custom domain. For more information, see [Learn more](https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site) (DeprecatedIPError). We recommend you add an `A` record pointed to our IP addresses, or an `ALIAS` record pointing to `uafcsc.github.io`.

**Comment by CyberAngler93** [comment]
I have submitted a ticket to OIT to correct the old DNS record.

**Comment by CyberAngler93** [comment]
I talked with OIT and the configuration on OITs side looks correct. We both agreed with dig and nslookup that we were targeting the correct DNS servers. 

The only difference I could see is the ordering of the A records. they do not match what uafcsc.github.io has an I wonder if they are just comparing the content of dig based on what they said to do for troubleshooting

```
dig www.csc.uaf.edu                                                                                              ─╯

; <<>> DiG 9.16.1-Ubuntu <<>> www.csc.uaf.edu
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 41130
;; flags: qr rd ad; QUERY: 1, ANSWER: 5, AUTHORITY: 0, ADDITIONAL: 0
;; WARNING: recursion requested but not available

;; QUESTION SECTION:
;www.csc.uaf.edu.               IN      A

;; ANSWER SECTION:
www.csc.uaf.edu.        0       IN      CNAME   uafcsc.github.io.
uafcsc.github.io.       0       IN      A       185.199.111.153
uafcsc.github.io.       0       IN      A       185.199.108.153
uafcsc.github.io.       0       IN      A       185.199.109.153
uafcsc.github.io.       0       IN      A       185.199.110.153

;; Query time: 10 msec
;; SERVER: 172.26.224.1#53(172.26.224.1)
```

vs 
```
 dig uafcsc.github.io                                                                                                                                                                                                                            ─╯

; <<>> DiG 9.16.1-Ubuntu <<>> uafcsc.github.io
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 20367
;; flags: qr rd ad; QUERY: 1, ANSWER: 4, AUTHORITY: 0, ADDITIONAL: 0
;; WARNING: recursion requested but not available

;; QUESTION SECTION:
;uafcsc.github.io.              IN      A

;; ANSWER SECTION:
uafcsc.github.io.       0       IN      A       185.199.110.153
uafcsc.github.io.       0       IN      A       185.199.111.153
uafcsc.github.io.       0       IN      A       185.199.108.153
uafcsc.github.io.       0       IN      A       185.199.109.153

;; Query time: 10 msec
;; SERVER: 172.26.224.1#53(172.26.224.1)
;; WHEN: Mon Aug 16 14:16:25 -08 2021
;; MSG SIZE  rcvd: 114
```


Overall I believe the claim that we are configured wrong it incorrect. Based on the documentation that I found for GitHub pages the correct DNS is `185.199.111.153 185.199.110.153 185.199.109.153 185.199.108.153` 

I am going to close this issue for now as our system is serving correctly and our `ALIAS` RECORD and `A` RECORD match the docs from GitHub pages.
